# Generated by Django 6.0.6 on 2026-06-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_operacion', models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=20)),
                ('tipo_propiedad', models.CharField(choices=[('Casa', 'Casa'), ('Terreno', 'Terreno'), ('Parcela', 'Parcela'), ('Sitio', 'Sitio'), ('Local Comercial', 'Local Comercial')], max_length=50)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Vendida', 'Vendida'), ('Arrendada', 'Arrendada')], default='Disponible', max_length=20)),
                ('precio', models.IntegerField()),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('dormitorios', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('metros_cuadrados', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('destacada', models.BooleanField(default=False)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('codigo_propiedad', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propiedades.propiedad')),
            ],
        ),
    ]
